### PR TITLE
Export block in Quilting is now stand-alone

### PR DESCRIPTION
**Pull request by ethanmriley**
Added radial ordering and rounding to the exportAsCSV block, making the additional C++ parser unnecessary. Deleted the extra blocks that were copied over when we reset the Quilting repo.

### CODE REVIEW

**Comment by ethanmriley** [comment]
Should be good to go now. Blocks.json and stage.xml are both overwritten with what appears to be git info in the previous version. Not sure how that happened.

**Comment by SillyInventor** [comment]
poke

**Comment by SillyInventor** [comment]
@ethanmriley Poke

**Comment by ethanmriley** [comment]
Stage.xml is now reset to a good (imo) default, and I removed oldQuilting.zip.

**Comment by SillyInventor** [comment]
Did you remember to push your changes?

**Pull request merged**
